### ISSUE TITLE
Script dies if icon isn't found / support icon.png in the same path as the script

### ISSUE THREAD

**Issue by ghost** [sorin-ionescu/weechat-growl#9]
```
    22:03:58  weechat     | python: loading script "/home/voltagex/.weechat/python/growl.py"
    22:03:59  weechat     | python: registered script "growl", version 1.0.5 (Sends Growl notifications upon events.)
    22:03:59  weechat     | python: stdout/stderr: Traceback (most recent call last):
    22:03:59  weechat     | python: stdout/stderr:   File "/home/voltagex/.weechat/python/growl.py", line 501, in <module>
    22:03:59  weechat     | python: stdout/stderr:     main()
    22:03:59  weechat     | python: stdout/stderr:   File "/home/voltagex/.weechat/python/growl.py", line 450, in main
    22:03:59  weechat     | python: stdout/stderr:     weechat.config_get_plugin('icon')), "rb").read()
    22:03:59  weechat     | python: stdout/stderr: IOError: [Errno 2] No such file or directory: '/home/voltagex/.weechat/icon.png'
    22:03:59  weechat =!= | python: unable to parse file "/home/voltagex/.weechat/python/growl.py"
```

The icon is actually in ~/voltagex/.weechat/python/icon.png, along with growl.py

Should the script look for the icon in the same path as the script itself?

Should a missing icon only be a warning?

**Comment by sorin-ionescu** [comment]
This was introduced in #8. @eddiezane, can you fix it, please?

**Comment by eddiezane** [comment]
Sorry about that! A missing icon should throw a warning, so I'll add that in. 

@sorin-ionescu what are your thoughts on default icon location? I went along with what you originally had in the readme and figured if people wanted to stray from that, they would modify the script.

**Comment by sorin-ionescu** [comment]
Whatever is easiest. I suppose, whatever is in the README.
